{{- if .Values.standalone.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: edc-standalone-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edc-standalone.standalone.labels" . | nindent 4 }}
data:
  configuration.properties: |
{{ include "edc-standalone.config.properties" .Values.standalone.config | nindent 4 }}
{{- end }} 