{{- if .Values.standalone.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: edc-standalone-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edc-standalone.standalone.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.standalone.secrets.apiKey | b64enc | quote }}
  jwt-secret: {{ .Values.standalone.secrets.jwtSecret | b64enc | quote }}
{{- end }} 