{{- if .Values.rbac.enabled }}
{{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-cluster-role
  labels:
    {{- include "edc-monitoring.monitoring.labels" . | nindent 4 }}
    app: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-cluster-role-binding
  labels:
    {{- include "edc-monitoring.monitoring.labels" . | nindent 4 }}
    app: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccounts.monitoring.prometheus.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }} 