{{- if .Values.serviceAccounts.create }}
{{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.enabled }}
{{- if .Values.serviceAccounts.monitoring.prometheus.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.monitoring.prometheus.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edc-monitoring.monitoring.labels" . | nindent 4 }}
    app: prometheus
  {{- with .Values.serviceAccounts.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }} 