{{- if .Values.rbac.enabled }}
{{- if .Values.standalone.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edc-control-plane-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edc-standalone.standalone.labels" . | nindent 4 }}
    app: edc-control-plane
    component: edc
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  - pods
  - services
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edc-control-plane-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edc-standalone.standalone.labels" . | nindent 4 }}
    app: edc-control-plane
    component: edc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edc-control-plane-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccounts.standalone.controlPlane.name }}
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edc-data-plane-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edc-standalone.standalone.labels" . | nindent 4 }}
    app: edc-data-plane
    component: edc
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  - pods
  - services
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edc-data-plane-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edc-standalone.standalone.labels" . | nindent 4 }}
    app: edc-data-plane
    component: edc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edc-data-plane-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccounts.standalone.dataPlane.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}

{{- if .Values.peer.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edc-peer-control-plane-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edc-standalone.peer.labels" . | nindent 4 }}
    app: edc-peer-control-plane
    component: edc-peer
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  - pods
  - services
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edc-peer-control-plane-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edc-standalone.peer.labels" . | nindent 4 }}
    app: edc-peer-control-plane
    component: edc-peer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edc-peer-control-plane-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccounts.peer.controlPlane.name }}
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edc-peer-data-plane-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edc-standalone.peer.labels" . | nindent 4 }}
    app: edc-peer-data-plane
    component: edc-peer
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  - pods
  - services
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edc-peer-data-plane-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edc-standalone.peer.labels" . | nindent 4 }}
    app: edc-peer-data-plane
    component: edc-peer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edc-peer-data-plane-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccounts.peer.dataPlane.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}

{{- end }} 