{{- if .Values.serviceAccounts.create }}
{{- if .Values.standalone.enabled }}
{{- if .Values.serviceAccounts.standalone.controlPlane.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.standalone.controlPlane.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edc-standalone.standalone.labels" . | nindent 4 }}
    app: edc-control-plane
    component: edc
  {{- with .Values.serviceAccounts.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- if .Values.serviceAccounts.standalone.dataPlane.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.standalone.dataPlane.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edc-standalone.standalone.labels" . | nindent 4 }}
    app: edc-data-plane
    component: edc
  {{- with .Values.serviceAccounts.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}

{{- if .Values.peer.enabled }}
{{- if .Values.serviceAccounts.peer.controlPlane.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.peer.controlPlane.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edc-standalone.peer.labels" . | nindent 4 }}
    app: edc-peer-control-plane
    component: edc-peer
  {{- with .Values.serviceAccounts.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- if .Values.serviceAccounts.peer.dataPlane.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.peer.dataPlane.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edc-standalone.peer.labels" . | nindent 4 }}
    app: edc-peer-data-plane
    component: edc-peer
  {{- with .Values.serviceAccounts.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}

{{- end }} 