{{- if .Values.peer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: edc-peer-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edc-standalone.peer.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.peer.secrets.apiKey | b64enc | quote }}
  jwt-secret: {{ .Values.peer.secrets.jwtSecret | b64enc | quote }}
{{- end }} 