# Default values for edc-monitoring
# This is a YAML-formatted file.

# Global configuration
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""
  nameOverride: ""
  fullnameOverride: ""

# Monitoring configuration
monitoring:
  enabled: true
  
  # Prometheus configuration
  prometheus:
    enabled: true
    image:
      repository: prom/prometheus
      tag: "v2.48.0"
      pullPolicy: IfNotPresent
    
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "100m"
    
    config:
      scrape_interval: "10s"
      metrics_path: "/metrics"
    
    service:
      type: ClusterIP
      port: 9090
  
  # Grafana configuration
  grafana:
    enabled: true
    image:
      repository: grafana/grafana
      tag: "10.2.0"
      pullPolicy: IfNotPresent
    
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "100m"
    
    adminPassword: "admin123"
    disablePlugins: true
    
    service:
      type: ClusterIP
      port: 3000
  
  # Loki configuration
  loki:
    enabled: true
    image:
      repository: grafana/loki
      tag: "2.9.0"
      pullPolicy: IfNotPresent
    
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "100m"
    
    service:
      type: ClusterIP
      port: 3100

# Ingress configuration for monitoring
ingress:
  enabled: true
  className: "nginx"
  
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  
  hosts:
    - host: prometheus.local
      paths:
        - path: /
          pathType: Prefix
          service:
            name: prometheus
            port: 9090
    - host: grafana.local
      paths:
        - path: /
          pathType: Prefix
          service:
            name: grafana
            port: 3000

# RBAC configuration
rbac:
  enabled: true
  create: true

# Service accounts
serviceAccounts:
  create: true
  annotations: {}
  
  # Monitoring service accounts
  monitoring:
    prometheus:
      create: true
      name: "prometheus-sa"

promtail:
  enabled: true
  resources:
    requests:
      memory: "64Mi"
      cpu: "25m"
    limits:
      memory: "128Mi"
      cpu: "50m" 